/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary List all active (non-expired) posts
 */
export declare const ListPostsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    category: zod.ZodEnum<["akcii", "znyzhky", "novyny"]>;
    title: zod.ZodString;
    price: zod.ZodString;
    imageUrl: zod.ZodNullable<zod.ZodString>;
    createdAt: zod.ZodDate;
    expiresAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    category: "akcii" | "znyzhky" | "novyny";
    title: string;
    price: string;
    imageUrl: string | null;
    createdAt: Date;
    expiresAt: Date;
}, {
    id: number;
    category: "akcii" | "znyzhky" | "novyny";
    title: string;
    price: string;
    imageUrl: string | null;
    createdAt: Date;
    expiresAt: Date;
}>;
export declare const ListPostsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    category: zod.ZodEnum<["akcii", "znyzhky", "novyny"]>;
    title: zod.ZodString;
    price: zod.ZodString;
    imageUrl: zod.ZodNullable<zod.ZodString>;
    createdAt: zod.ZodDate;
    expiresAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    category: "akcii" | "znyzhky" | "novyny";
    title: string;
    price: string;
    imageUrl: string | null;
    createdAt: Date;
    expiresAt: Date;
}, {
    id: number;
    category: "akcii" | "znyzhky" | "novyny";
    title: string;
    price: string;
    imageUrl: string | null;
    createdAt: Date;
    expiresAt: Date;
}>, "many">;
/**
 * @summary Create a new post (admin only)
 */
export declare const CreatePostBody: zod.ZodObject<{
    category: zod.ZodEnum<["akcii", "znyzhky", "novyny"]>;
    title: zod.ZodString;
    price: zod.ZodString;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    expiresAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    category: "akcii" | "znyzhky" | "novyny";
    title: string;
    price: string;
    expiresAt: Date;
    imageUrl?: string | null | undefined;
}, {
    category: "akcii" | "znyzhky" | "novyny";
    title: string;
    price: string;
    expiresAt: Date;
    imageUrl?: string | null | undefined;
}>;
export declare const CreatePostResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    category: zod.ZodEnum<["akcii", "znyzhky", "novyny"]>;
    title: zod.ZodString;
    price: zod.ZodString;
    imageUrl: zod.ZodNullable<zod.ZodString>;
    createdAt: zod.ZodDate;
    expiresAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    category: "akcii" | "znyzhky" | "novyny";
    title: string;
    price: string;
    imageUrl: string | null;
    createdAt: Date;
    expiresAt: Date;
}, {
    id: number;
    category: "akcii" | "znyzhky" | "novyny";
    title: string;
    price: string;
    imageUrl: string | null;
    createdAt: Date;
    expiresAt: Date;
}>;
/**
 * @summary Delete a post (admin only)
 */
export declare const DeletePostParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeletePostResponse: zod.ZodVoid;
/**
 * @summary Request a presigned upload URL (admin only)
 */
export declare const RequestUploadUrlBody: zod.ZodObject<{
    name: zod.ZodString;
    size: zod.ZodNumber;
    contentType: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
    size: number;
    contentType: string;
}, {
    name: string;
    size: number;
    contentType: string;
}>;
export declare const RequestUploadUrlResponse: zod.ZodObject<{
    uploadURL: zod.ZodString;
    objectPath: zod.ZodString;
    metadata: zod.ZodOptional<zod.ZodObject<{
        name: zod.ZodString;
        size: zod.ZodNumber;
        contentType: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        name: string;
        size: number;
        contentType: string;
    }, {
        name: string;
        size: number;
        contentType: string;
    }>>;
}, "strip", zod.ZodTypeAny, {
    uploadURL: string;
    objectPath: string;
    metadata?: {
        name: string;
        size: number;
        contentType: string;
    } | undefined;
}, {
    uploadURL: string;
    objectPath: string;
    metadata?: {
        name: string;
        size: number;
        contentType: string;
    } | undefined;
}>;
/**
 * Returns the public key clients need to subscribe to push notifications
 * @summary Get the VAPID public key
 */
export declare const GetVapidPublicKeyResponse: zod.ZodObject<{
    publicKey: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    publicKey: string;
}, {
    publicKey: string;
}>;
/**
 * Registers a browser push subscription so the server can send it notifications
 * @summary Subscribe to push notifications
 */
export declare const SubscribeToNotificationsBody: zod.ZodObject<{
    endpoint: zod.ZodString;
    keys: zod.ZodObject<{
        p256dh: zod.ZodString;
        auth: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        p256dh: string;
        auth: string;
    }, {
        p256dh: string;
        auth: string;
    }>;
}, "strip", zod.ZodTypeAny, {
    keys: {
        p256dh: string;
        auth: string;
    };
    endpoint: string;
}, {
    keys: {
        p256dh: string;
        auth: string;
    };
    endpoint: string;
}>;
export declare const SubscribeToNotificationsResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    endpoint: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    endpoint: string;
}, {
    id: number;
    endpoint: string;
}>;
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
//# sourceMappingURL=api.d.ts.map